Traceback (most recent call last):
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Configure the model and start training
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, Y_train, epochs=20, batch_size=250, verbose=1, validation_split=0.2)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mInternalError[0m                             Traceback (most recent call last)
[1;32m<ipython-input-11-2412e7be1fab>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# Configure the model and start training[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [0mmodel[0m[1;33m.[0m[0mcompile[0m[1;33m([0m[0mloss[0m[1;33m=[0m[1;34m'categorical_crossentropy'[0m[1;33m,[0m [0moptimizer[0m[1;33m=[0m[1;34m'adam'[0m[1;33m,[0m [0mmetrics[0m[1;33m=[0m[1;33m[[0m[1;34m'accuracy'[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 3[1;33m [0mmodel[0m[1;33m.[0m[0mfit[0m[1;33m([0m[0mX_train[0m[1;33m,[0m [0mY_train[0m[1;33m,[0m [0mepochs[0m[1;33m=[0m[1;36m20[0m[1;33m,[0m [0mbatch_size[0m[1;33m=[0m[1;36m250[0m[1;33m,[0m [0mverbose[0m[1;33m=[0m[1;36m1[0m[1;33m,[0m [0mvalidation_split[0m[1;33m=[0m[1;36m0.2[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m~\miniconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py[0m in [0;36mfit[1;34m(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)[0m
[0;32m   1237[0m                                         [0msteps_per_epoch[0m[1;33m=[0m[0msteps_per_epoch[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1238[0m                                         [0mvalidation_steps[0m[1;33m=[0m[0mvalidation_steps[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1239[1;33m                                         validation_freq=validation_freq)
[0m[0;32m   1240[0m [1;33m[0m[0m
[0;32m   1241[0m     def evaluate(self,

[1;32m~\miniconda3\envs\tensorflow\lib\site-packages\keras\engine\training_arrays.py[0m in [0;36mfit_loop[1;34m(model, fit_function, fit_inputs, out_labels, batch_size, epochs, verbose, callbacks, val_function, val_inputs, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq)[0m
[0;32m    194[0m                     [0mins_batch[0m[1;33m[[0m[0mi[0m[1;33m][0m [1;33m=[0m [0mins_batch[0m[1;33m[[0m[0mi[0m[1;33m][0m[1;33m.[0m[0mtoarray[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    195[0m [1;33m[0m[0m
[1;32m--> 196[1;33m                 [0mouts[0m [1;33m=[0m [0mfit_function[0m[1;33m([0m[0mins_batch[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    197[0m                 [0mouts[0m [1;33m=[0m [0mto_list[0m[1;33m([0m[0mouts[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    198[0m                 [1;32mfor[0m [0ml[0m[1;33m,[0m [0mo[0m [1;32min[0m [0mzip[0m[1;33m([0m[0mout_labels[0m[1;33m,[0m [0mouts[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\backend.py[0m in [0;36m__call__[1;34m(self, inputs)[0m
[0;32m   3725[0m         [0mvalue[0m [1;33m=[0m [0mmath_ops[0m[1;33m.[0m[0mcast[0m[1;33m([0m[0mvalue[0m[1;33m,[0m [0mtensor[0m[1;33m.[0m[0mdtype[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   3726[0m       [0mconverted_inputs[0m[1;33m.[0m[0mappend[0m[1;33m([0m[0mvalue[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 3727[1;33m     [0moutputs[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_graph_fn[0m[1;33m([0m[1;33m*[0m[0mconverted_inputs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   3728[0m [1;33m[0m[0m
[0;32m   3729[0m     [1;31m# EagerTensor.numpy() will often make a copy to ensure memory safety.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py[0m in [0;36m__call__[1;34m(self, *args, **kwargs)[0m
[0;32m   1549[0m       [0mTypeError[0m[1;33m:[0m [0mFor[0m [0minvalid[0m [0mpositional[0m[1;33m/[0m[0mkeyword[0m [0margument[0m [0mcombinations[0m[1;33m.[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1550[0m     """
[1;32m-> 1551[1;33m     [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_call_impl[0m[1;33m([0m[0margs[0m[1;33m,[0m [0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1552[0m [1;33m[0m[0m
[0;32m   1553[0m   [1;32mdef[0m [0m_call_impl[0m[1;33m([0m[0mself[0m[1;33m,[0m [0margs[0m[1;33m,[0m [0mkwargs[0m[1;33m,[0m [0mcancellation_manager[0m[1;33m=[0m[1;32mNone[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py[0m in [0;36m_call_impl[1;34m(self, args, kwargs, cancellation_manager)[0m
[0;32m   1589[0m       raise TypeError("Keyword arguments {} unknown. Expected {}.".format(
[0;32m   1590[0m           list(kwargs.keys()), list(self._arg_keywords)))
[1;32m-> 1591[1;33m     [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_call_flat[0m[1;33m([0m[0margs[0m[1;33m,[0m [0mself[0m[1;33m.[0m[0mcaptured_inputs[0m[1;33m,[0m [0mcancellation_manager[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1592[0m [1;33m[0m[0m
[0;32m   1593[0m   [1;32mdef[0m [0m_filtered_call[0m[1;33m([0m[0mself[0m[1;33m,[0m [0margs[0m[1;33m,[0m [0mkwargs[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py[0m in [0;36m_call_flat[1;34m(self, args, captured_inputs, cancellation_manager)[0m
[0;32m   1690[0m       [1;31m# No tape is watching; skip to running the function.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1691[0m       return self._build_call_outputs(self._inference_function.call(
[1;32m-> 1692[1;33m           ctx, args, cancellation_manager=cancellation_manager))
[0m[0;32m   1693[0m     forward_backward = self._select_forward_and_backward_functions(
[0;32m   1694[0m         [0margs[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py[0m in [0;36mcall[1;34m(self, ctx, args, cancellation_manager)[0m
[0;32m    543[0m               [0minputs[0m[1;33m=[0m[0margs[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    544[0m               [0mattrs[0m[1;33m=[0m[1;33m([0m[1;34m"executor_type"[0m[1;33m,[0m [0mexecutor_type[0m[1;33m,[0m [1;34m"config_proto"[0m[1;33m,[0m [0mconfig[0m[1;33m)[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 545[1;33m               ctx=ctx)
[0m[0;32m    546[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    547[0m           outputs = execute.execute_with_cancellation(

[1;32m~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\execute.py[0m in [0;36mquick_execute[1;34m(op_name, num_outputs, inputs, attrs, ctx, name)[0m
[0;32m     65[0m     [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m     66[0m       [0mmessage[0m [1;33m=[0m [0me[0m[1;33m.[0m[0mmessage[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 67[1;33m     [0msix[0m[1;33m.[0m[0mraise_from[0m[1;33m([0m[0mcore[0m[1;33m.[0m[0m_status_to_exception[0m[1;33m([0m[0me[0m[1;33m.[0m[0mcode[0m[1;33m,[0m [0mmessage[0m[1;33m)[0m[1;33m,[0m [1;32mNone[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     68[0m   [1;32mexcept[0m [0mTypeError[0m [1;32mas[0m [0me[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m     69[0m     keras_symbolic_tensors = [

[1;32m~\miniconda3\envs\tensorflow\lib\site-packages\six.py[0m in [0;36mraise_from[1;34m(value, from_value)[0m

[1;31mInternalError[0m:  Blas GEMM launch failed : a.shape=(250, 784), b.shape=(784, 350), m=250, n=350, k=784
	 [[node dense_1/MatMul (defined at C:\Users\Samuel\miniconda3\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py:3009) ]] [Op:__inference_keras_scratch_graph_900]

Function call stack:
keras_scratch_graph

InternalError:  Blas GEMM launch failed : a.shape=(250, 784), b.shape=(784, 350), m=250, n=350, k=784
	 [[node dense_1/MatMul (defined at C:\Users\Samuel\miniconda3\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py:3009) ]] [Op:__inference_keras_scratch_graph_900]

Function call stack:
keras_scratch_graph


